-- Egbe Anom Supabase schema scaffold.
-- Apply in Supabase SQL editor or with psql before switching the app gateway.

create table if not exists public.products (
  id bigint primary key,
  category_id bigint,
  brand_id bigint,
  name text not null,
  fragrance_type text not null default 'Perfume',
  brand text not null default 'Egbe Anom',
  vendor text not null default 'Egbe Anom',
  item_location text not null default 'Main warehouse',
  sku text not null unique,
  notes text not null default '',
  size text not null default '50 ml',
  price numeric(10,2) not null default 0,
  cost numeric(10,2) not null default 0,
  stock integer not null default 0,
  sold integer not null default 0,
  reorder_point integer not null default 8,
  weight_oz numeric(10,2) not null default 8,
  length_in numeric(10,2) not null default 6,
  width_in numeric(10,2) not null default 3,
  height_in numeric(10,2) not null default 3,
  photo_url text not null default '',
  featured_color text not null default '#C88F52',
  sort_order integer not null default 10,
  is_active boolean not null default true,
  description text not null default '',
  ingredients text not null default '',
  top_notes text not null default '',
  heart_notes text not null default '',
  base_notes text not null default '',
  concentration text not null default 'Extrait de Parfum',
  gender text not null default 'Unisex',
  season text not null default 'Year-round',
  occasion text not null default 'Daily wear',
  family text not null default 'Woody',
  rating numeric(3,2) not null default 5,
  review_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint primary key,
  name text not null,
  description text not null default '',
  sort_order integer not null default 10,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brand_profiles (
  id bigint primary key,
  name text not null,
  history text not null default '',
  founded_year integer,
  country text not null default '',
  description text not null default '',
  logo_url text not null default '',
  sort_order integer not null default 10,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null,
  sku text not null,
  price numeric(10,2) not null default 0,
  stock integer not null default 0,
  reorder_point integer not null default 8,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products
  add column if not exists category_id bigint,
  add column if not exists brand_id bigint,
  add column if not exists fragrance_type text not null default 'Perfume',
  add column if not exists brand text not null default 'Egbe Anom',
  add column if not exists vendor text not null default 'Egbe Anom',
  add column if not exists item_location text not null default 'Main warehouse',
  add column if not exists notes text not null default '',
  add column if not exists size text not null default '50 ml',
  add column if not exists price numeric(10,2) not null default 0,
  add column if not exists cost numeric(10,2) not null default 0,
  add column if not exists stock integer not null default 0,
  add column if not exists sold integer not null default 0,
  add column if not exists reorder_point integer not null default 8,
  add column if not exists weight_oz numeric(10,2) not null default 8,
  add column if not exists length_in numeric(10,2) not null default 6,
  add column if not exists width_in numeric(10,2) not null default 3,
  add column if not exists height_in numeric(10,2) not null default 3,
  add column if not exists photo_url text not null default '',
  add column if not exists featured_color text not null default '#C88F52',
  add column if not exists sort_order integer not null default 10,
  add column if not exists is_active boolean not null default true,
  add column if not exists description text not null default '',
  add column if not exists ingredients text not null default '',
  add column if not exists top_notes text not null default '',
  add column if not exists heart_notes text not null default '',
  add column if not exists base_notes text not null default '',
  add column if not exists concentration text not null default 'Extrait de Parfum',
  add column if not exists gender text not null default 'Unisex',
  add column if not exists season text not null default 'Year-round',
  add column if not exists occasion text not null default 'Daily wear',
  add column if not exists family text not null default 'Woody',
  add column if not exists rating numeric(3,2) not null default 5,
  add column if not exists review_count integer not null default 0;

create table if not exists public.product_images (
  id bigint generated always as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  storage_path text not null default '',
  content_type text not null default 'image/png',
  file_size bigint not null default 0,
  alt_text text not null default '',
  sort_order integer not null default 10,
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.fragrance_notes (
  id bigint generated by default as identity primary key,
  name text not null unique,
  note_type text not null default 'Custom',
  family text not null default '',
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fragrance_families (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fragrance_seasons (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.fragrance_occasions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coupon_rules (
  id text primary key,
  code text not null unique,
  name text not null,
  discount_type text not null default 'percent',
  value numeric(10,2) not null default 0,
  minimum_spend numeric(10,2) not null default 0,
  usage_limit integer not null default 0,
  used integer not null default 0,
  starts_on text not null default '',
  ends_on text not null default '',
  is_active boolean not null default true,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_methods (
  id text primary key,
  name text not null,
  provider text not null,
  status text not null default 'Not connected',
  fee text not null default '',
  settlement text not null default '',
  is_enabled boolean not null default false,
  mode text not null default 'Test',
  public_key text not null default '',
  merchant_id text not null default '',
  webhook_url text not null default '',
  statement_descriptor text not null default 'EGBE ANOM',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shipping_options (
  id text primary key,
  name text not null,
  carrier text not null,
  service text not null,
  priority text not null default 'Standard',
  price numeric(10,2) not null default 0,
  estimated_days text not null default '3-5 business days',
  is_enabled boolean not null default true,
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_info (
  id text primary key default 'primary',
  store_name text not null default 'EgbeAnom Fragrance',
  display_name text not null default 'EgbeAnom Fragrance',
  banner_url text not null default '',
  logo_url text not null default '',
  address_line1 text not null default '',
  address_line2 text not null default '',
  city text not null default '',
  state text not null default '',
  postal_code text not null default '',
  country text not null default 'US',
  email text not null default '',
  phone text not null default '',
  fax text not null default '',
  facebook_url text not null default '',
  instagram_url text not null default '',
  tiktok_url text not null default '',
  x_url text not null default '',
  youtube_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tax_rules (
  id text primary key,
  name text not null,
  country text not null default 'US',
  state text not null default '',
  county text not null default '',
  city text not null default '',
  postal_code_prefix text not null default '',
  tax_type text not null default 'sales',
  rate numeric(8,5) not null default 0,
  is_vat boolean not null default false,
  is_enabled boolean not null default true,
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_blocks (
  id text primary key,
  title text not null,
  placement text not null,
  body text not null default '',
  sort_order integer not null default 10,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  order_number text not null unique,
  custom_customer_id text,
  customer_name text not null,
  email text not null,
  status text not null default 'Pending',
  financial_status text not null default 'Pending',
  fulfillment_status text not null default 'Unfulfilled',
  subtotal numeric(10,2) not null default 0,
  discount_total numeric(10,2) not null default 0,
  tax_total numeric(10,2) not null default 0,
  shipping_total numeric(10,2) not null default 0,
  grand_total numeric(10,2) not null default 0,
  payment_provider text not null default '',
  payment_reference text not null default '',
  coupon_code text not null default '',
  item_count integer not null default 0,
  shipping_carrier text not null default '',
  shipping_service text not null default '',
  shipping_priority text not null default 'Standard',
  tracking_number text not null default '',
  label_status text not null default 'Not requested',
  invoice_number text not null default '',
  invoice_snapshot jsonb not null default '{}'::jsonb,
  tax_breakdown jsonb not null default '[]'::jsonb,
  shipping_address jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders drop constraint if exists orders_fulfillment_status_check;
alter table public.orders add constraint orders_fulfillment_status_check
  check (
    fulfillment_status in (
      'Unfulfilled',
      'Pending',
      'Processing',
      'Being picked',
      'Label Printed',
      'Label created',
      'Sent',
      'Shipped',
      'Delivered',
      'Cancelled'
    )
  );

create table if not exists public.order_items (
  id bigint generated always as identity primary key,
  order_id text not null,
  product_id bigint references public.products(id) on delete set null,
  sku text not null default '',
  product_name text not null,
  size text not null default '',
  quantity integer not null default 1,
  unit_price numeric(10,2) not null default 0,
  line_total numeric(10,2) not null default 0,
  item_location text not null default '',
  product_photo_url text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.store_reviews (
  id text primary key,
  scope text not null default 'product',
  product_id bigint references public.products(id) on delete set null,
  customer_email text not null default '',
  author text not null,
  rating integer not null default 5,
  title text not null default '',
  body text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.store_reviews
  add column if not exists customer_email text not null default '';

create table if not exists public.order_surveys (
  id text primary key,
  order_id text not null,
  customer_email text not null,
  author text not null default 'Verified customer',
  rating integer not null default 5,
  title text not null default '',
  body text not null default '',
  would_recommend boolean not null default true,
  is_anonymous boolean not null default false,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_notifications (
  id text primary key,
  type text not null,
  title text not null,
  message text not null default '',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.store_customers (
  id text primary key,
  auth_user_id uuid references auth.users(id) on delete set null,
  name text not null default 'Customer',
  email text not null unique,
  joined_days_ago integer not null default 0,
  orders integer not null default 0,
  lifetime_value numeric(10,2) not null default 0,
  segment text not null default 'Customer',
  referral_code text not null default '',
  referral_credits numeric(10,2) not null default 0,
  phone text not null default '',
  order_count integer not null default 0,
  accepts_marketing boolean not null default false,
  is_blocked boolean not null default false,
  created_ip text not null default '',
  last_login_ip text not null default '',
  last_login_at timestamptz,
  blocked_reason text not null default '',
  address_line1 text not null default '',
  address_line2 text not null default '',
  city text not null default '',
  county text not null default '',
  state text not null default '',
  postal_code text not null default '',
  country text not null default 'US',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.store_customers
  add column if not exists auth_user_id uuid references auth.users(id) on delete set null,
  add column if not exists joined_days_ago integer not null default 0,
  add column if not exists orders integer not null default 0,
  add column if not exists lifetime_value numeric(10,2) not null default 0,
  add column if not exists segment text not null default 'Customer',
  add column if not exists referral_code text not null default '',
  add column if not exists referral_credits numeric(10,2) not null default 0,
  add column if not exists is_blocked boolean not null default false,
  add column if not exists created_ip text not null default '',
  add column if not exists last_login_ip text not null default '',
  add column if not exists last_login_at timestamptz,
  add column if not exists blocked_reason text not null default '',
  add column if not exists address_line1 text not null default '',
  add column if not exists address_line2 text not null default '',
  add column if not exists city text not null default '',
  add column if not exists county text not null default '',
  add column if not exists state text not null default '',
  add column if not exists postal_code text not null default '',
  add column if not exists country text not null default 'US';

create table if not exists public.backend_users (
  id text primary key,
  auth_user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null unique,
  role text not null default 'staff',
  is_active boolean not null default true,
  is_blocked boolean not null default false,
  created_ip text not null default '',
  last_login_ip text not null default '',
  blocked_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.backend_users
  add column if not exists auth_user_id uuid references auth.users(id) on delete set null,
  add column if not exists role text not null default 'staff',
  add column if not exists is_active boolean not null default true,
  add column if not exists is_blocked boolean not null default false,
  add column if not exists created_ip text not null default '',
  add column if not exists last_login_ip text not null default '',
  add column if not exists blocked_reason text not null default '';

create table if not exists public.blocked_ips (
  ip_address text primary key,
  reason text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "public product image object read" on storage.objects;
drop policy if exists "backend admins upload product image objects" on storage.objects;
drop policy if exists "backend admins update product image objects" on storage.objects;
drop policy if exists "backend admins delete product image objects" on storage.objects;

create policy "public product image object read" on storage.objects
  for select using (bucket_id = 'product-images');

create or replace function public.is_backend_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.backend_users
    where auth_user_id = auth.uid()
      and is_active = true
      and is_blocked = false
      and role in ('owner', 'admin', 'manager', 'staff')
  );
$$;

alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_images enable row level security;
alter table public.categories enable row level security;
alter table public.brand_profiles enable row level security;
alter table public.fragrance_notes enable row level security;
alter table public.fragrance_families enable row level security;
alter table public.fragrance_seasons enable row level security;
alter table public.fragrance_occasions enable row level security;
alter table public.coupon_rules enable row level security;
alter table public.payment_methods enable row level security;
alter table public.shipping_options enable row level security;
alter table public.store_info enable row level security;
alter table public.tax_rules enable row level security;
alter table public.content_blocks enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.store_reviews enable row level security;
alter table public.order_surveys enable row level security;
alter table public.store_customers enable row level security;
alter table public.backend_users enable row level security;
alter table public.blocked_ips enable row level security;
alter table public.site_settings enable row level security;
alter table public.admin_notifications enable row level security;

create policy "public product read" on public.products
  for select using (is_active = true or public.is_backend_admin());
create policy "public product image read" on public.product_images
  for select using (true);
create policy "public product variant read" on public.product_variants
  for select using (is_active = true or public.is_backend_admin());
create policy "public catalog metadata read" on public.categories
  for select using (is_visible = true or public.is_backend_admin());
create policy "public brand read" on public.brand_profiles
  for select using (is_visible = true or public.is_backend_admin());
create policy "public fragrance note read" on public.fragrance_notes
  for select using (true);
create policy "public fragrance family read" on public.fragrance_families
  for select using (true);
create policy "public fragrance season read" on public.fragrance_seasons
  for select using (true);
create policy "public fragrance occasion read" on public.fragrance_occasions
  for select using (true);
create policy "public shipping read" on public.shipping_options
  for select using (is_enabled = true or public.is_backend_admin());
create policy "public store info read" on public.store_info
  for select using (true);
create policy "public tax rule read" on public.tax_rules
  for select using (is_enabled = true or public.is_backend_admin());
create policy "public content read" on public.content_blocks
  for select using (is_visible = true or public.is_backend_admin());
create policy "public site setting read" on public.site_settings
  for select using (is_public = true or public.is_backend_admin());
create policy "public approved review read" on public.store_reviews
  for select using (
    status = 'approved'
    or customer_email = (auth.jwt() ->> 'email')
    or public.is_backend_admin()
  );
create policy "public enabled payment read" on public.payment_methods
  for select using (is_enabled = true or public.is_backend_admin());

create policy "customers own profile read" on public.store_customers
  for select using (auth_user_id = auth.uid() or public.is_backend_admin());
create policy "customers own email profile read" on public.store_customers
  for select using (
    email = (auth.jwt() ->> 'email')
    or public.is_backend_admin()
  );
create policy "customers own profile insert" on public.store_customers
  for insert with check (auth_user_id = auth.uid() or public.is_backend_admin());
create policy "customers own profile update" on public.store_customers
  for update using (auth_user_id = auth.uid() or public.is_backend_admin())
  with check (auth_user_id = auth.uid() or public.is_backend_admin());
create policy "customers own email profile update" on public.store_customers
  for update using (
    email = (auth.jwt() ->> 'email')
    or public.is_backend_admin()
  )
  with check (
    auth_user_id = auth.uid()
    or public.is_backend_admin()
  );

create policy "backend users can read own profile" on public.backend_users
  for select using (auth_user_id = auth.uid() or public.is_backend_admin());
create policy "backend users can read own email profile" on public.backend_users
  for select using (
    email = (auth.jwt() ->> 'email')
    or public.is_backend_admin()
  );
create policy "backend users can link own email profile" on public.backend_users
  for update using (
    email = (auth.jwt() ->> 'email')
    or public.is_backend_admin()
  )
  with check (
    auth_user_id = auth.uid()
    or public.is_backend_admin()
  );
create policy "backend admins manage backend users" on public.backend_users
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());

create policy "authenticated users can create orders" on public.orders
  for insert with check (auth.role() = 'authenticated');
create policy "customers read own orders" on public.orders
  for select using (
    public.is_backend_admin()
    or email = (auth.jwt() ->> 'email')
  );
create policy "customers read own order items" on public.order_items
  for select using (
    public.is_backend_admin()
    or exists (
      select 1 from public.orders
      where orders.id::text = order_items.order_id
        and orders.email = (auth.jwt() ->> 'email')
    )
  );

create policy "authenticated users create reviews" on public.store_reviews
  for insert with check (
    auth.role() = 'authenticated'
    and customer_email = (auth.jwt() ->> 'email')
  );
create policy "backend admins manage reviews" on public.store_reviews
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "verified customers create order surveys" on public.order_surveys
  for insert with check (
    auth.role() = 'authenticated'
    and exists (
      select 1 from public.orders
      where orders.id::text = order_surveys.order_id
        and orders.email = (auth.jwt() ->> 'email')
    )
  );
create policy "customers read own surveys" on public.order_surveys
  for select using (
    public.is_backend_admin()
    or customer_email = (auth.jwt() ->> 'email')
  );

create policy "backend admins manage products" on public.products
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage categories" on public.categories
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage product images" on public.product_images
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage product variants" on public.product_variants
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage notes" on public.fragrance_notes
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage store info" on public.store_info
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage tax rules" on public.tax_rules
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage orders" on public.orders
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage order items" on public.order_items
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage surveys" on public.order_surveys
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage settings" on public.site_settings
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage blocked ips" on public.blocked_ips
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());
create policy "backend admins manage admin notifications" on public.admin_notifications
  for all using (public.is_backend_admin()) with check (public.is_backend_admin());

create policy "backend admins upload product image objects" on storage.objects
  for insert with check (
    bucket_id = 'product-images'
    and public.is_backend_admin()
  );
create policy "backend admins update product image objects" on storage.objects
  for update using (
    bucket_id = 'product-images'
    and public.is_backend_admin()
  ) with check (
    bucket_id = 'product-images'
    and public.is_backend_admin()
  );
create policy "backend admins delete product image objects" on storage.objects
  for delete using (
    bucket_id = 'product-images'
    and public.is_backend_admin()
  );
